services:
  db:
    image: postgres:latest
    container_name: flightsdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flights
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
    container_name: fligths
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      PG_URL: postgres://postgres:postgres@flightsdb:5432/flights?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
volumes:
  pgdata: